SELECT MERKMAL.MENENNMAS, TEIL.TETEILNR, TEIL.TEBEZEICH, TEIL.TEARBEITSGANG, WERTEVAR.WVUNTERS, WERTEVAR.WVMERKMAL, WERTEVAR.WVWERTNR, 
WERTEVAR.WVWERT, WERTEVAR.WVDATZEIT, WERTEVAR.WVATTRIBUT, WERTEVAR.WVPRUEFER, WERTEVAR.WVMASCHINE, WERTEVAR.WV0014,
MERKMAL.MEMERKBEZ, MERKMAL.MEUGW, MERKMAL.MEOGW, MERKMAL.MEMERKKLASSE, ALARM_VALUES.ALARM_EW, WERTEVAR.WVTEIL  
FROM((
	( [WERTEVAR] left join TEIL on[WERTEVAR].WVTEIL = TEIL.TETEIL) 
		left join MERKMAL on [WERTEVAR].WVMERKMAL = MERKMAL.MEMERKMAL and WERTEVAR.WVTEIL = MERKMAL.METEIL )
		left join ALARM_VALUES on [WERTEVAR].WVWERTNR = ALARM_VALUES.K0000 and WERTEVAR.WVTEIL = ALARM_VALUES.K1000  and WERTEVAR.WVMERKMAL = ALARM_VALUES.K2000)
        where WV0014 ='2010202216' 
		order by WERTEVAR.WVWERTNR asc